system/modules/dashboard/controllers/CobindingController.php
<?php

/**
 * CobindingController.class.file
 * 
 * @author mumu <2317216477@qq.com>
 * @link http://www.ibos.com.cn/
 * @copyright Copyright &copy; 2015 IBOS Inc
 */
/**
 * 酷办公绑定控制器
 * 
 * @package application.modules.dashboard.controllers
 * @author mumu <2317216477@qq.com>
 * 
 */

namespace application\modules\dashboard\controllers;

use application\core\model\Log;
use application\core\utils\Env;
use application\core\utils\IBOS;
use application\modules\main\model\Setting;
use application\modules\message\core\co\CoApi;
use application\modules\message\core\co\CodeApi;
use application\modules\user\model\UserBinding;
use application\modules\user\utils\User as UserUtil;

class CobindingController extends CoController {

	/**
	 * 首页视图
	 */
	public function actionIndex() {
		//首先根据setting表里的accesstoken获取企业管理员的登录信息
		$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
		$res = $this->getCoUser( isset( $coinfo['accesstoken'] ) ? $coinfo['accesstoken'] : ''  );
		if ( $res['code'] == CodeApi::SUCCESS ) {
			//本地accesstoken登录成功
			$param = array( 'data' => $res['data'] );
			$aeskey = Setting::model()->fetchSettingValueByKey( 'aeskey' );
			if ( $this->isBinding ) {
				//酷办公是否匹配oa
				$coIsBindOa = $this->coIsBindOa( isset( $coinfo['corptoken'] ) ? $coinfo['corptoken'] : '', $aeskey );
				if ( $coIsBindOa ) {
					$params = $this->returnCorp( $param );
					$params['data']['accesstoken'] = $coinfo['accesstoken'];
					$this->render( 'index', $params );
				} else {
					//否则需要重新登录
					$this->render( 'login' );
				}
			} else { //如果本地没有绑定
				if ( $res['data']['role'] == 'admin' ) {
					$corpRes = CoApi::getInstance()->getCorpByCorpToken( isset( $coinfo['corptoken'] ) ? $coinfo['corptoken'] : ''  );
					if ( $corpRes['code'] == CodeApi::SUCCESS ) {
						if ( !empty( $corpRes['data']['aeskey'] ) ) { //已绑定
							if ( strcmp( $aeskey, $corpRes['data']['aeskey'] ) != 0 ) {//但是企业不一致，显示解绑
								$param['op'] = 'unbindingoa';
								$param['data']['systemurl'] = $corpRes['data']['systemurl'];
								$this->render( 'index', $param );
							} else {
								$unit = unserialize( Setting::model()->fetchSettingValueByKey( 'unit' ) );
								//远程已经绑定（有aeskey），但是aeskey相等，能到这里说明是本地cobinding是0，同时又是超管。可是其实这个情况已经算是绑定了的
								Setting::model()->updateSettingValueByKey( 'cobinding', 1 );
								$params = $this->returnCorp( $param );
								$params['data']['accesstoken'] = $coinfo['accesstoken'];
								$this->render( 'index', $params );
							}
						} else { //远程未绑定OA
							$unit = unserialize( Setting::model()->fetchSettingValueByKey( 'unit' ) );
							if ( strcmp( $unit['corpcode'], $corpRes['data']['code'] ) == 0 ) { //相等，表示企业代码统一
								$post = array(
									'aeskey' => $aeskey,
									'systemurl' => $unit['systemurl'],
									'name' => $unit['fullname'],
									'shortname' => $unit['shortname']
								);
								$updateRes = CoApi::getInstance()->updateCorpByCorpToken( $coinfo['corptoken'], $post );
								if ( $updateRes['code'] == CodeApi::SUCCESS ) {
									Setting::model()->updateSettingValueByKey( 'cobinding', 1 );
								}
								$params = $this->returnCorp( $param );
								$params['data']['accesstoken'] = $coinfo['accesstoken'];
								$this->render( 'index', $params );
							} else {
								//不想等，企业代码不一致，把本地的和酷办公的输出
								$param['op'] = 'oacode';
								$param['data']['oacode'] = $unit['corpcode'];
								$param['data']['cocode'] = $corpRes['data']['code'];
								$this->render( 'index', $param );
							}
						}
					} else {
						//远程是管理员，本地accesstoken成功登录，但是corptoken过期或者没有，这个情况……什么时候出现的orz
						$this->render( 'login', array( 'mobile' => $coinfo['mobile'], 'readonly' => true ) );
					}
				} else {
					//不是管理员
					if ( $res['data']['isjoin'] == 'no' ) {//没有加入企业，则创建新的企业
						$unit = unserialize( Setting::model()->fetchSettingValueByKey( 'unit' ) );
						$param['op'] = 'usercreate';
						$param['data']['corpname'] = $unit['fullname'];
						$param['data']['corpshortname'] = $unit['shortname'];
						$param['data']['corpcode'] = $unit['corpcode'];
						$this->render( 'index', $param );
					} else {
						/**
						 * 加入了企业，则：
						 * 1、退出并创建新企业
						 * 或者
						 * 2、重新登录
						 * 现在使用同一个视图
						 */
						$param['op'] = 'userquitorlogin';
						$this->render( 'index', $param );
					}
				}
			}
		} else {
			//根据Setting coinfo保存的accesstoken尝试登录
			if ( $this->isBinding && !empty( $coinfo['mobile'] ) ) {
				//说明过期，获取本地保存的mobile，写成readonly形式
				$this->render( 'login', array( 'mobile' => $coinfo['mobile'], 'readonly' => true ) );
			} else {
				$this->render( 'login' );
			}
		}
	}

	public function actionLogin() {
		$this->render( 'login' );
	}

	/**
	 * 酷办公是否绑定oa，用aeskey判断，安装的时候用systemurl去验证
	 * @param type $corptoken
	 * @param type $aeskey
	 * @return boolean
	 */
	public function coIsBindOa( $corptoken, $aeskey ) {
		$corpRes = CoApi::getInstance()->getCorpByCorpToken( $corptoken );
		if ( $corpRes['code'] == CodeApi::SUCCESS ) {
			return !strcmp( $aeskey, $corpRes['data']['aeskey'] );
		} else {
			return false;
		}
	}

	/**
	 * 返回企业显示所需要的数据
	 * @param type $param
	 * @return array
	 */
	public function returnCorp( $param ) {
		//匹配就显示该企业的信息
		$oaUser = UserUtil::loadUser();
		$userBinding = UserBinding::model()->fetchAllByApp( 'co' );
		$param['op'] = 'index';
		$param['data']['oaUser'] = $oaUser;
		$param['data']['userBinding'] = $userBinding;
		return $param;
	}

	/**
	 * 前端ajax请求的登录地址
	 */
	public function actionLoginco() {
		$mobile = Env::getRequest( 'mobile' );
		$password = Env::getRequest( 'password' );
		if ( $this->isBinding ) {
			$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
			if ( !empty( $coinfo['mobile'] ) && $coinfo['mobile'] != $mobile ) {
				$this->ajaxReturn( array(
					'isSuccess' => false,
					'msg' => '请用oa绑定的酷办公的超级管理员账号登录'
				) );
			}
		}
		$tokenRes = CoApi::getInstance()->getCoToken( $mobile, $password );
		if ( $tokenRes['code'] == CodeApi::SUCCESS ) {
			//只有在绑定的情况下，如果登录的不是对应的oa的账号，就提示不匹配
			if ( $this->isBinding ) {
				$corpRes = CoApi::getInstance()->getCorpByCorpToken( $tokenRes['data']['corptoken'] );
				$aeskey = Setting::model()->fetchSettingValueByKey( 'aeskey' );
				if ( !empty( $corpRes['data']['aeskey'] ) ) {
					if ( strcmp( $aeskey, $corpRes['data']['aeskey'] ) != 0 ) {
						$this->ajaxReturn( array(
							'isSuccess' => false,
							'msg' => '酷办公账号和oa不匹配，请重新登录', //出现这个情况，是本地accesstoken过期，且远程aeskey错误
						) );
					}
				} else {
					Setting::model()->updateSettingValueByKey( 'cobinding', 0 );
					$this->ajaxReturn( array(
						'isSuccess' => true,
					) );
				}
			}
			/**
			 * 1、没有绑定，登录保存登录信息
			 * 2、绑定了，绑定的酷办公账号对应找到的企业aeskey和本地的一致
			 * 最开始两种状态：
			 * a、没有绑定酷办公
			 * b、绑定了酷办公，此时本地保存了超管的mobile，尝试用超管账号登录失败后，才会来到登录的这个方法
			 * 所以一定对应2的情况
			 */
			$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
			$coinfo['corptoken'] = $tokenRes['data']['corptoken'];
			$coinfo['accesstoken'] = $tokenRes['data']['accesstoken'];
			$coinfo['guid'] = $tokenRes['data']['guid'];
			$coinfo['mobile'] = $mobile;
			Setting::model()->updateSettingValueByKey( 'coinfo', serialize( $coinfo ) );
			$this->ajaxReturn( array(
				'isSuccess' => true,
			) );
		} else {
			$this->ajaxReturn( array(
				'isSuccess' => false,
				'msg' => $tokenRes['message'],
			) );
		}
	}

	/**
	 * 统一ibos和酷办公代码，以远程的为准
	 */
	public function actionUnifyCode() {
		$code = Env::getRequest( 'code' );
		$unit = unserialize( Setting::model()->fetchSettingValueByKey( 'unit' ) );
		$unit['corpcode'] = $code;
		Setting::model()->updateSettingValueByKey( 'unit', serialize( $unit ) );
		Setting::model()->updateSettingValueByKey( 'cobinding', 1 );
		$this->ajaxReturn( array(
			'isSuccess' => true,
		) );
	}

	/**
	 * 酷办公解绑原有OA后，绑定现登录OA，并将现有OA与酷办公绑定
	 */
	public function actionImUnbindingIbos() {
		$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
		$unit = unserialize( Setting::model()->fetchSettingValueByKey( 'unit' ) );
		$aeskey = Setting::model()->fetchSettingValueByKey( 'aeskey' );
		$corptoken = $coinfo['corptoken'];
		$post = array(
			'aeskey' => $aeskey,
			'systemurl' => $unit['systemurl'],
			'name' => $unit['fullname'],
			'shortname' => $unit['shortname']
		);
		$res = CoApi::getInstance()->updateCorpByCorpToken( $corptoken, $post );
		if ( $res['code'] == CodeApi::SUCCESS ) {
			Setting::model()->updateSettingValueByKey( 'cobinding', 1 );
			$this->ajaxReturn( array(
				'isSuccess' => true,
			) );
		} else {
			$this->ajaxReturn( array(
				'isSuccess' => false,
				'msg' => $res['message'],
			) );
		}
	}

	/**
	 * 解绑酷办公
	 */
	public function actionUnbinding() {
		//请求远程，删除aeskey
		$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
		$res = CoApi::getInstance()->updateCorpByCorpToken( $coinfo['corptoken'], array( 'aeskey' => '' ) );
		if ( $res['code'] == CodeApi::SUCCESS ) {
			Setting::model()->updateSettingValueByKey( 'cobinding', 0 );
			Setting::model()->updateSettingValueByKey( 'coinfo', '' );
			$this->ajaxReturn( array( 'isSuccess' => true, ) );
		} else {
			$this->ajaxReturn( array(
				'isSuccess' => false,
				'msg' => $res['message']
			) );
		}
	}
	/**
	 * 退出企业
	 */
	public function actionQuitCo() {
		$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
		$corptoken = $coinfo['corptoken'];
		$res = CoApi::getInstance()->quitCorpByCorpToken( $corptoken );
		if ( $res['code'] == CodeApi::SUCCESS ) {
			$this->ajaxReturn( array(
				'isSuccess' => true,
			) );
		} else {
			$this->ajaxReturn( array(
				'isSuccess' => false,
				'msg' => $res['message'],
			) );
		}
	}
	/**
	 * 创建企业并且绑定
	 */
	public function actionCreateAndBinding() {
		//创建企业
		$unit = unserialize( Setting::model()->fetchSettingValueByKey( 'unit' ) );
		$coinfo = unserialize( Setting::model()->fetchSettingValueByKey( 'coinfo' ) );
		$accesstoken = $coinfo['accesstoken'];
		$post = array(

system/modules/dashboard/views/cobinding/banding.php
<form action="#" method="post" id="bind_info_form">
    <div class="dialog-info-wrap">
        <div class="match-btn-wrap">
            <button type="button" class="btn btn-primary" data-action="matchAction">自动匹配酷办公与OA相同的名字</button>
        </div>
        <div class="manual-bind-wrap">
            <div class="toggle-hook">
                <span class="info-toggle-hook active" data-action="infoDisplayToggle" data-self="user_info_wrap" data-target="result_info_wrap">
                    <i class="caret"></i>
                    <span>手动绑定</span>
                </span>
            </div>
            <div id="user_info_wrap" style="display:none;">
                <div class="clearfix match-type-wrap">
                    <div class="span6">
                        <label for="iboscoUser" class="xwb">酷办公用户</label>
                        <select id="iboscoUser" size="10">
                        </select>
                    </div>
                    <div class="span6">
                        <label for="oaUser" class="xwb">OA用户</label>
                        <select id="oaUser" size="10">
                        	<option value="1">管理员</option>
                        </select>
                    </div>
                </div>
                <button type="button" class="btn mls" data-action="ceratRelationship" id="relative_btn">建立绑定关系</button>
            </div>
        </div>
        <div class="manual-bind-wrap mbs">
            <div class="toggle-hook">
                <span class="info-toggle-hook active" data-action="infoDisplayToggle" data-self="result_info_wrap" data-target="user_info_wrap">
                    <i class="caret"></i>
                    <span>已绑定</span>
                    <span id="binding_user" class="fsl xcbu"></span>
                    <span>人，</span>
                    <span class="mlm">新添加</span>
                    <span class="fsl" id="addCount">0</span>
                    <span>人</span>
                </span>
            </div>
        </div>
        <div id="result_info_wrap">
            <div class="clearfix result-opt-wrap">
                <button type="button" class="btn pull-left" data-action="clearAll">清空</button>
            </div>
            <div class="page-list">
                <table class="table table-hover table-striped result-info-table" id="result_info_table">
                    <thead>
                        <tr>
                            <th>酷办公用户姓名</th>
                            <th>OA用户姓名</th>
                            <th width="40">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <input type="hidden" name="map" id="result_map_value" value="">
                <input type="hidden" name="_csrf" value='<?php echo IBOS::$app->getRequest()->getCsrfToken(); ?>' />
            </div>
        </div>
    </div>
</form>
<script src="<?php echo $assetUrl; ?>/js/db_cobinding_banding.js"></script>

system/modules/dashboard/views/cobinding/index.php
<link href="<?php echo $this->getAssetUrl(); ?>/css/ibosco.css" type="text/css" rel="stylesheet">
<div class="ct">
	<div class="clearfix">
		<h1 class="mt">酷办公</h1>
		<ul class="mn">
			<li>
				<span>酷办公绑定</span>
			</li>
			<li>
				<a href="<?php echo $this->createUrl( 'cosync/index' ) ?>">部门及用户同步</a>
			</li>
		</ul>
	</div>
	<div>
		<!-- 企业信息 start -->
		<div class="ctb">
			<h2 class="st">酷办公绑定</h2>
			<div class="co-result-wrap">
				<!-- 当只是酷办公注册的新账号，没用创建且加入企业时，不显示企业信息栏，即rbox-top -->
				<div class="rbox-top clearfix">
					<div class="logo-wrap pull-left">
						<img src="<?php echo $data['corplogo'] ?>" alt="企业LOGO">
					</div>
					<div class="rbox-info-wrap pull-left">
						<p class="fsl xwb xcm mbs"><?php echo $data['corpshortname']; ?></p>
						<p class="mbs">
							<span class="tcm">全称：</span>
							<span><?php echo $data['corpname'] ?></span>
						</p>
						<p>
							<span class="tcm">企业代码：</span>
							<span><?php echo $data['corpcode'] ?></span>
						</p>
					</div>
					<?php if ( $op == 'index' ): ?>
						<!-- 当用户OA已绑定酷办公，且登录账号为该企业酷办公超管账号时，显示解绑操作 -->
						<div class="rbox-opt-wrap pull-right">
							<a href="javascript:;" data-action="unbindingIbosCo">解除绑定</a>
						</div>
					<?php endif; ?>
				</div>
				<?php if ( $op == 'index' ): ?>
				<?php if($op == "first"){ ?>
					<div id="rbox_box">
						<!-- 酷办公账号匹配，登录成功 -->
						<div class="rbox-box">
							<!-- 如果是第一次未同步的 -->
							<div>
								<p class="xac fsl first-box">哎呀，你还没同步部门及用户哦！</p>
								<hr>
								<div class="xac">
									<a class="btn btn-primary" href="<?php echo $this->createUrl( 'cosync/index' ) ?>">同步部门及用户</button>
								</div>
							</div>
						</div>
					</div>
				<?php }else{ ?>
					<div id="rbox_box">
						<!-- 酷办公账号匹配，登录成功 -->
						<div class="rbox-box">
							<!-- 同步以后 -->
							<div class="clearfix">
								<div class="rinfo-box">
									<p class="tits">已绑定</p>
									<p>
										<span class="fsf"><?php echo count( $data['userBinding'] ) ?></span>
										<span>人</span>
									</p>
								</div>
								<div class="rinfo-box">
									<p class="tits">未绑定</p>
									<p>
										<span class="fsf"><?php echo count( $data['oaUser'] ) - count( $data['userBinding'] ); ?></span>
										<span>人</span>
									</p>
								</div>
								<button type="button" class="btn btn-primary binding-btn" data-action="bindingIbosCo" data-token="<?php echo $data['accesstoken'] ?>">绑定酷办公用户</button>
							</div>
						</div>
					</div>	
				<?php } ?>
					<?php endif; ?>
					<?php if ( $op == 'unbindingoa' ): ?>
						<!-- 本地没有绑定酷办公，但酷办公已绑定其他OA -->
						<div class="rbox-box">
							<div class="warning-box">
								<div class="warning-box-content xac">
									<i class="o-warning-tip mb"></i>
									<p class="fsm mbs">
										<span><?php echo $data['corpshortname'] ?> 已绑定过IBOS地址 “</span>
										<span class="xcm xwb"><?php echo $data['systemurl'] ?></span>
										<span> ”，</span>
									</p>
									<p class="fsm">如需关联当前地址，请解绑后进行。</p>
								</div>
								<div class="warning-box-footer">
									<a href="<?php echo $this->createUrl( 'cobinding/login' ); ?>">
										<i class="o-link-logo"></i>
										<span>重新登陆</span>
									</a>
									<button type="button" class="btn btn-primary unbinding-btn" data-action="imUnbindingIbos">立即解绑</button>
								</div>
							</div>
						</div>
					<?php endif; ?>
					<!-- 本地没有绑定酷办公，且酷办公没有绑定OA,但企业代码不一致 -->
					<?php if ( $op == 'oacode' ): ?>
						<div class="rbox-box">
							<div class="warning-box">
								<div class="warning-box-content xac">
									<i class="o-warning-tip mb"></i>
									<p class="fsm mbs">
										<span>酷办公企业代码</span>
										<span class="xcm xwb">[</span>
										<span class="xcm xwb"><?php echo $data['cocode'] ?></span>
										<span class="xcm xwb">]</span>
										<span>与本地</span>
										<span class="xcm xwb">[</span>
										<span class="xcm xwb"><?php echo $data['oacode'] ?></span>
										<span class="xcm xwb">]</span>
										<span>不一致，请统一！</span>
									</p>
									<div>
										<span>我要统一为：</span>
										<label class="radio dib">
											<input type="radio" name="code" class="radio" checked="checked" value="<?php echo $data['cocode'] ?>" />
											<span><?php echo $data['cocode'] ?></span>
										</label>
									</div>
								</div>
								<div class="warning-box-footer">
									<a href="<?php echo $this->createUrl( 'cobinding/login' ); ?>">
										<i class="o-link-logo"></i>
										<span>重新登陆</span>
									</a>
									<button type="button" class="btn btn-primary unify-code-btn" data-action="unifyCode">确定</button>
								</div>
							</div>
						</div>
					<?php endif; ?>
					<?php if ( $op == 'userquitorlogin' ): ?>
						<!-- 本地没有绑定酷办公，酷办公已绑定其它OA但不是企业超管 -->
						<div class="rbox-box">
							<div class="warning-box">
								<div class="warning-box-content xac">
									<i class="o-warning-tip mb"></i>
									<p class="fsm mbs">
										<span>你还不是</span>
										<span class="xcm xwb"><?php echo $data['corpshortname'] ?></span>
										<span>超级管理员，如需绑定请退出并创建新企业！</span>
									</p>
									<p class="fss tcm">注意：退出后你需要创建新企业完成绑定</p>
								</div>
								<div class="warning-box-footer">
									<a href="<?php echo $this->createUrl( 'cobinding/login' ); ?>">
										<i class="o-link-logo"></i>
										<span>重新登陆</span>
									</a>
									<button type="button" class="btn btn-primary unbinding-btn" data-action="exitBusiness">退出企业</button>
								</div>
							</div>
						</div>
					<?php endif; ?>
					<!-- 本地没有办法定酷办公，酷办公没有绑定其它OA但不是企业超管 -->
					<div class="rbox-box" style="display:none;">
						<div class="warning-box">
							<div class="warning-box-content xac">
								<i class="o-warning-tip mb"></i>
								<p class="fsm mbs">
									<span>你还不是</span>
									<span class="xcm xwb">优网科技</span>
									<span>超级管理员，无法进行绑定！</span>
								</p>
								<p>
									<span>请登录超级管理员</span>
									<span>ellenlun</span> 
									<span>进行操作。</span>
								</p>
							</div>
							<div class="warning-box-footer">
								<!-- 跳转到登录页 -->
								<a href="" class="btn btn-primary again-login-btn">重新登陆</a>
							</div>
						</div>
					</div>
					<!-- 本地没有办法定酷办公，没有加入酷办公企业 -->
					<?php if ( $op == 'usercreate' ): ?>
						<div class="rbox-box">
							<div class="warning-box">
								<div class="warning-box-content xac">
									<i class="o-warning-tip mb"></i>
									<p class="fsm xcm mbs">
										<span>你还没有企业，是否按如下信息创建企业绑定？</span>
									</p>
									<p class="mbs">
										<span>创建后的企业简称、全称可在酷办公后台修改</span>
									</p>
									<div class="xal cy-info-wrap">
										<p class="fss mbs">
											<span class="tcm">企业简称：</span>
											<span><?php echo $data['corpshortname'] ?></span>
										</p>
										<p class="fss mbs">
											<span class="tcm">全称：</span>
											<span><?php echo $data['corpname'] ?></span>
										</p>
										<p class="fss">
											<span class="tcm">企业代码：</span>
											<span><?php echo $data['corpcode'] ?></span>
										</p>
									</div>
								</div>
								<div class="warning-box-footer">
									<a href="<?php echo $this->createUrl( 'cobinding/login' ); ?>">
										<i class="o-link-logo"></i>
										<span>重新登陆</span>
									</a>
									<button type="button" class="btn btn-primary unbinding-btn" data-action="createAndBindingIbosCo">创建并绑定</button>
								</div>
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function() {
		Ibos.app.s({
	"CoCompanyName": "<?php echo $data['corpshortname']; ?>",
	"IbosCompanyName": "<?php echo $data['corpshortname']; ?>"
		});
	});
</script>
<script type="text/javascript" src="<?php echo $this->getAssetUrl(); ?>/js/ibosco.js"></script>

system/modules/dashboard/views/cobinding/login.php
<link href="<?php echo $this->getAssetUrl(); ?>/css/ibosco.css" type="text/css" rel="stylesheet">
<div class="ct">
	<div class="clearfix">
		<h1 class="mt">酷办公</h1>
		<ul class="mn">
			<li>
				<span>酷办公绑定</span>
			</li>
			<li>
				<a href="<?php echo $this->createUrl( 'cosync/index' ) ?>">部门及用户同步</a>
			</li>
		</ul>
	</div>
	<div>
		<!-- 企业信息 start -->
		<div class="ctb">
			<h2 class="st">酷办公绑定</h2>
			<div class="co-banding-wrap">
				<!-- 当只是酷办公注册的新账号，没用创建且加入企业时，不显示企业信息栏，即rbox-top -->
				<div class="box-top">
					<form action="#" method="post" id="ibosco_login_form">
						<p class="xwb mb">请登录IBOS · 酷办公</p>
						<div>
							<input type="text" name="mobile" id="mobile" class="phone-input" placeholder="手机" nofocus <?php
							if ( isset( $readonly ) ) { ?>readonly value ="<?php echo $mobile;?>" <?php }?>/>
								   <input type="password" name="password" id="password" class="password-input mls" placeholder="密码" nofocus />
							<button type="button" class="btn btn-primary opt-btn mls" data-action="loginIbosCo">登录</button>
							<a href="http://www.ibos.cn/" target="_blank" class="btn mlm opt-btn">注册</a>
						</div>
					</form>
				</div>
				<div class="box-body">
					<div class="logo-tip-wrap">
						<i class="o-logo-tip"></i>
					</div>
					<i class="o-image-tip"></i>
				</div>
			</div>
		</div>
	</div>
</div>
<script src='<?php echo STATICURL; ?>/js/lib/formValidator/formValidator.packaged.js?<?php echo VERHASH; ?>'></script>
<script type="text/javascript" src="<?php echo $this->getAssetUrl(); ?>/js/iboscologin.js"></script>